# Local administrator password of the Ops VM, generated by Terraform (stored in the protected layer 1 state;
# a later private agent step copies it to the admin vault)
resource "random_password" "ops_vm_admin" {
  length           = 24
  special          = true
  override_special = "!#%*-_=+?"
  min_lower        = 2
  min_upper        = 2
  min_numeric      = 2
  min_special      = 2
}

# Windows Ops VM without a public IP address, member of the ops-vm application security group
resource "azurerm_network_interface" "ops_vm" {
  name                = "nic-vm-sits-${local.environment}-ops-${local.region_code}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  tags                = local.tags

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = azurerm_subnet.main["snet-ops"].id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_network_interface_application_security_group_association" "ops_vm" {
  network_interface_id          = azurerm_network_interface.ops_vm.id
  application_security_group_id = azurerm_application_security_group.main["ops-vm"].id
}

resource "azurerm_windows_virtual_machine" "ops" {
  name                  = "vm-sits-${local.environment}-ops-${local.region_code}"
  computer_name         = "ops-${local.environment}"
  resource_group_name   = data.azurerm_resource_group.network.name
  location              = data.azurerm_resource_group.network.location
  # Standard_D2s_v6: the subscription has no Dsv5 quota in Sweden Central (limit 0); v6 sizes use the NVMe disk controller
  size                  = "Standard_D2s_v6"
  disk_controller_type  = "NVMe"
  zone                  = "1"
  admin_username        = "opsadmin"
  admin_password        = random_password.ops_vm_admin.result
  network_interface_ids = [azurerm_network_interface.ops_vm.id]
  secure_boot_enabled   = true
  vtpm_enabled          = true
  tags                  = local.tags

  os_disk {
    name                 = "osdisk-vm-sits-${local.environment}-ops-${local.region_code}"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2022-datacenter-azure-edition"
    version   = "latest"
  }
}

# Bastion Developer: free tier for Dev and Test, needs no own subnet and no public IP address
resource "azurerm_bastion_host" "developer" {
  name                = "bas-sits-${local.environment}-${local.region_code}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  sku                 = "Developer"
  virtual_network_id  = azurerm_virtual_network.main.id
  tags                = local.tags
}

output "ops_vm_admin_username" {
  value = azurerm_windows_virtual_machine.ops.admin_username
}

output "ops_vm_admin_password" {
  value     = random_password.ops_vm_admin.result
  sensitive = true
}
