# Local administrator password of the Ops VM, generated by Terraform (stored in the protected layer 1 state;
# a later private agent step copies it to the admin vault). In production it is the emergency account only.
resource "random_password" "ops_vm_admin" {
  length           = 24
  special          = true
  override_special = "!#%*-_=+?"
  min_lower        = 2
  min_upper        = 2
  min_numeric      = 2
  min_special      = 2
}

# Windows Ops VM without a public IP address, member of the ops-vm application security group
resource "azurerm_network_interface" "ops_vm" {
  name                = "nic-vm-sits-${local.environment}-ops-${local.region_code}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  tags                = local.tags

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = azurerm_subnet.main["snet-ops"].id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_network_interface_application_security_group_association" "ops_vm" {
  network_interface_id          = azurerm_network_interface.ops_vm.id
  application_security_group_id = azurerm_application_security_group.main["ops-vm"].id
}

resource "azurerm_windows_virtual_machine" "ops" {
  name                = "vm-sits-${local.environment}-ops-${local.region_code}"
  computer_name       = "ops-${local.environment}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  # Same size as development and testing (v6 sizes use the NVMe disk controller)
  size                  = "Standard_D2s_v6"
  disk_controller_type  = "NVMe"
  zone                  = "1"
  admin_username        = "opsadmin"
  admin_password        = random_password.ops_vm_admin.result
  network_interface_ids = [azurerm_network_interface.ops_vm.id]
  secure_boot_enabled   = true
  vtpm_enabled          = true
  tags                  = local.tags

  # System identity for Microsoft Entra ID sign-in (AADLoginForWindows)
  identity {
    type = "SystemAssigned"
  }

  os_disk {
    name                 = "osdisk-vm-sits-${local.environment}-ops-${local.region_code}"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2022-datacenter-azure-edition"
    version   = "latest"
  }
}

# Microsoft Entra ID sign-in to the Ops VM; the production account has Virtual Machine User Login from layer 0
resource "azurerm_virtual_machine_extension" "aad_login" {
  name                       = "AADLoginForWindows"
  virtual_machine_id         = azurerm_windows_virtual_machine.ops.id
  publisher                  = "Microsoft.Azure.ActiveDirectory"
  type                       = "AADLoginForWindows"
  type_handler_version       = "2.0"
  auto_upgrade_minor_version = true
  tags                       = local.tags
}

# Bastion Basic in its own subnet with a public address (see the Bastion NSG for the admin_ip deviation)
resource "azurerm_public_ip" "bastion" {
  name                = "pip-sits-${local.environment}-bastion-${local.region_code}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  sku                 = "Standard"
  allocation_method   = "Static"
  zones               = ["1"]
  tags                = local.tags
}

resource "azurerm_bastion_host" "basic" {
  name                = "bas-sits-${local.environment}-${local.region_code}"
  resource_group_name = data.azurerm_resource_group.network.name
  location            = data.azurerm_resource_group.network.location
  sku                 = "Basic"
  tags                = local.tags

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.main["AzureBastionSubnet"].id
    public_ip_address_id = azurerm_public_ip.bastion.id
  }

  # The Bastion NSG must be in place before Bastion is created
  depends_on = [azurerm_network_security_rule.main, azurerm_subnet_network_security_group_association.main]
}

output "ops_vm_admin_username" {
  value = azurerm_windows_virtual_machine.ops.admin_username
}

output "ops_vm_admin_password" {
  value     = random_password.ops_vm_admin.result
  sensitive = true
}
